# Generated by Django 5.2 on 2025-04-11 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='linked',
            new_name='liked',
        ),
    ]
